#!/usr/bin/env python3
"""
Generate the catalog seed Flyway migration from the legacy Pet Store populate XML.

This is a one-way migration tool: it reads the original
`Populate-UTF8.xml` (from the Java Pet Store 1.3.1 distribution) and emits idempotent-ordered
SQL INSERTs matching the V1 catalog schema. Keeping this as code (rather than hand-written SQL)
makes the seed reproducible and auditable — re-run it if the source data ever changes.

Usage:
    python3 extract_catalog_seed.py [SOURCE_XML] > ../../src/main/resources/db/migration/V2__catalog_seed.sql

SOURCE_XML defaults to the in-repo provenance copy at ./legacy/Populate-UTF8.xml.

Mappings:
  * xml:lang "en-US" -> DB locale "en_US" (legacy stored underscore form; cf. Profile/PreferredLanguage)
  * <Attribute> elements map positionally to attr1..attr5 (the legacy item_details columns)
  * Categories have Name+Image; Products/Items add Description; Items add ListPrice/UnitCost
"""
from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

DEFAULT_SRC = Path(__file__).parent / "legacy" / "Populate-UTF8.xml"
MAX_ATTRS = 5


def load_catalog(path: Path) -> ET.Element:
    raw = path.read_text(encoding="utf-8")
    # The document declares an internal DTD subset that pulls in external parameter entities
    # (dtds/*.dtd). We do not validate; strip the DOCTYPE so a plain parser accepts the body.
    raw = re.sub(r"<!DOCTYPE.*?\]>", "", raw, flags=re.DOTALL)
    return ET.fromstring(raw)


def q(value: str | None) -> str:
    """SQL string literal with single-quote escaping; NULL for missing."""
    if value is None:
        return "NULL"
    return "'" + value.strip().replace("'", "''") + "'"


def num(value: str) -> str:
    return value.strip()


def locale_of(el: ET.Element) -> str:
    lang = el.get("{http://www.w3.org/XML/1998/namespace}lang") or el.get("lang") or "en-US"
    return lang.replace("-", "_")


def text(el: ET.Element, tag: str) -> str | None:
    child = el.find(tag)
    return child.text if child is not None and child.text is not None else None


def main() -> None:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    root = load_catalog(src)
    catalog = root.find("Catalog")

    out = sys.stdout
    out.write("-- V2 — Catalog seed data\n")
    out.write("-- GENERATED by tools/seed-import/extract_catalog_seed.py from the legacy\n")
    out.write(f"-- {src.name}. Do not edit by hand; re-run the generator instead.\n\n")

    cats, cat_details = [], []
    prods, prod_details = [], []
    items, item_details = [], []

    for cat in catalog.find("Categories").findall("Category"):
        cid = cat.get("id")
        cats.append(f"insert into category (catid) values ({q(cid)});")
        for d in cat.findall("CategoryDetails"):
            cat_details.append(
                "insert into category_details (catid, name, image, descn, locale) values "
                f"({q(cid)}, {q(text(d,'Name'))}, {q(text(d,'Image'))}, {q(text(d,'Description'))}, {q(locale_of(d))});"
            )

    for p in catalog.find("Products").findall("Product"):
        pid, cid = p.get("id"), p.get("category")
        prods.append(f"insert into product (productid, catid) values ({q(pid)}, {q(cid)});")
        for d in p.findall("ProductDetails"):
            prod_details.append(
                "insert into product_details (productid, locale, name, image, descn) values "
                f"({q(pid)}, {q(locale_of(d))}, {q(text(d,'Name'))}, {q(text(d,'Image'))}, {q(text(d,'Description'))});"
            )

    for it in catalog.find("Items").findall("Item"):
        iid, pid = it.get("id"), it.get("product")
        items.append(f"insert into item (itemid, productid) values ({q(iid)}, {q(pid)});")
        for d in it.findall("ItemDetails"):
            attrs = [a.text for a in d.findall("Attribute")][:MAX_ATTRS]
            attrs += [None] * (MAX_ATTRS - len(attrs))
            attr_sql = ", ".join(q(a) for a in attrs)
            item_details.append(
                "insert into item_details (itemid, listprice, unitcost, locale, image, descn, "
                "attr1, attr2, attr3, attr4, attr5) values "
                f"({q(iid)}, {num(text(d,'ListPrice'))}, {num(text(d,'UnitCost'))}, {q(locale_of(d))}, "
                f"{q(text(d,'Image'))}, {q(text(d,'Description'))}, {attr_sql});"
            )

    for title, rows in [
        ("categories", cats), ("category_details", cat_details),
        ("products", prods), ("product_details", prod_details),
        ("items", items), ("item_details", item_details),
    ]:
        out.write(f"-- {title} ({len(rows)})\n")
        out.write("\n".join(rows))
        out.write("\n\n")

    sys.stderr.write(
        f"generated: {len(cats)} categories, {len(cat_details)} category_details, "
        f"{len(prods)} products, {len(prod_details)} product_details, "
        f"{len(items)} items, {len(item_details)} item_details\n"
    )


if __name__ == "__main__":
    main()
