-- V3 — Identity: application users
--
-- Replaces the legacy sign-on component's container-managed CMP `User(username, password)`
-- entity (schema was generated by the app server, never shipped as DDL). Per ADR-0005 security
-- is intentionally upgraded rather than reproduced bug-for-bug: passwords are BCrypt-hashed, so
-- the column is sized for a bcrypt digest ($2a$… ~60 chars) with headroom.

create table users (
    username     varchar(80)  not null,
    password     varchar(100) not null,
    enabled      boolean      not null default true,
    constraint pk_users primary key (username)
);
