-- V4 — Orders
--
-- Durable order records — behavior the legacy storefront did NOT have (it streamed orders to the
-- OPC over JMS and kept nothing). This is a deliberate enhancement recorded in ADR-0006 / risk R8.
-- The order is a point-in-time snapshot: line descriptions and prices are copied at checkout so a
-- later catalog change never rewrites history.

create table orders (
    order_id     varchar(36)    not null,
    username     varchar(80)    not null,
    total        decimal(10, 2) not null,
    status       varchar(20)    not null,
    placed_at    timestamp      not null,
    ship_name    varchar(120)   not null,
    ship_address varchar(255)   not null,
    ship_city    varchar(120)   not null,
    ship_email   varchar(255)   not null,
    constraint pk_orders primary key (order_id)
);

create table order_lines (
    id          bigint         generated by default as identity,
    order_id    varchar(36)    not null,
    itemid      varchar(10)    not null,
    description varchar(255),
    unitprice   decimal(10, 2) not null,
    quantity    int            not null,
    linetotal   decimal(10, 2) not null,
    constraint pk_order_lines primary key (id),
    constraint fk_order_lines_order foreign key (order_id) references orders (order_id)
);

create index idx_orders_username on orders (username);
create index idx_order_lines_order on order_lines (order_id);
